name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 🛎️
#         uses: actions/checkout@v2.3.1

#       - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: |
#           yarn
#           yarn run build

#       - name: Deploy 🚀
#         uses: JamesIves/github-pages-deploy-action@v4.2.2
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: build # The folder the action should deploy.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: blog/.vuepress/dist
          CNAME: https://blog.mayaqiang.vip
